Repository GoogleCloudPlatform/iot-core-micropython, pull requests merged in 2019-07, with the labels that each got.

#6 Blink led when processing and sending data
  main.py
Labels: enhancement

#5 Use values from config for MQTT endpoint
  main.py
Labels: bug, enhancement

#2 Ignore config.py to avoid accidental commits
  .gitignore
Labels: enhancement

#1 Replace lib with third_party in README
  README.md
Labels: bug, documentation

#4 Introduce a config section for device-specific values (like LED pin)
  config.py.example
  main.py
Labels: enhancement

#3 Print network and time info when the board starts
  main.py
Labels: enhancement

#9 Adds topic subscription
  main.py
Labels: enhancement
